# Generated by Django 4.2 on 2025-10-27 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_alter_student_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['course__code', 'name'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='assignmenttask',
            options={'permissions': [('add_assignmenttask_to_my_classes', 'Can add assignment task to my classes'), ('change_assignmenttask_from_my_classes', 'Can change assignment task from my classes'), ('view_assignmenttask_from_my_classes', 'Can view assignment task from my classes'), ('delete_assignmenttask_from_my_classes', 'Can delete assignment task from my classes')], 'verbose_name': 'Задача к заданию', 'verbose_name_plural': 'Задачи к заданиям'},
        ),
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['course__code', 'name'], 'verbose_name': 'Значок', 'verbose_name_plural': 'Значки'},
        ),
        migrations.AlterModelOptions(
            name='classbadge',
            options={'permissions': [('add_classbadge_to_my_classes', 'Can add class badge to my classes'), ('change_classbadge_from_my_classes', 'Can change class badge from my classes'), ('view_classbadge_from_my_classes', 'Can view class badge from my classes'), ('delete_classbadge_from_my_classes', 'Can delete class badge from my classes')], 'verbose_name': 'Значок Класса', 'verbose_name_plural': 'Значки Классов'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code', 'name'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='courseclass',
            options={'ordering': ['-end_date', 'code'], 'verbose_name': 'Класс Курса', 'verbose_name_plural': 'Классы Курсов'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'permissions': [('add_enrollment_to_my_classes', 'Can add enrollment to my classes'), ('change_enrollment_from_my_classes', 'Can change enrollment from my classes'), ('view_enrollment_from_my_classes', 'Can view enrollment from my classes'), ('delete_enrollment_from_my_classes', 'Can delete enrollment from my classes')], 'verbose_name': 'Запись на курс', 'verbose_name_plural': 'Записи на курсы'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('add_post_to_my_classes', 'Can add post to my classes'), ('change_post_from_my_classes', 'Can change post from my classes'), ('view_post_from_my_classes', 'Can view post from my classes'), ('delete_post_from_my_classes', 'Can delete post from my classes')], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['full_name'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['course__code', 'name'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='widget',
            options={'permissions': [('add_widget_to_my_classes', 'Can add widget to my classes'), ('change_widget_from_my_classes', 'Can change widget from my classes'), ('view_widget_from_my_classes', 'Can view widget from my classes'), ('delete_widget_from_my_classes', 'Can delete widget from my classes')], 'verbose_name': 'Виджет', 'verbose_name_plural': 'Виджеты'},
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Правильный ответ')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='course.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Вопрос к тесту',
                'verbose_name_plural': 'Вопросы к тестам',
            },
        ),
    ]
