# Generated by Django 4.2 on 2025-10-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='classbadgecriteria',
            options={'verbose_name': 'Критерий Значка Класса', 'verbose_name_plural': 'Критерии Значков Классов'},
        ),
        migrations.AlterModelOptions(
            name='classinstructor',
            options={'verbose_name': 'Преподаватель Класса', 'verbose_name_plural': 'Преподаватели Классов'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['full_name', 'user__username'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_diagnostic',
            field=models.BooleanField(default=False, verbose_name='Диагностическое задание'),
        ),
        migrations.AddField(
            model_name='student',
            name='diagnostic_completed',
            field=models.BooleanField(default=False, verbose_name='Диагностика пройдена'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Отменено'),
        ),
        migrations.AlterField(
            model_name='assignmenttask',
            name='points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Баллы (XP)'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Отменено'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.FloatField(verbose_name='Оценка (0-1)'),
        ),
    ]
